### ISSUE TITLE
Issues with AsynkThunk dispatching

### ISSUE THREAD

**Issue by las3r** [Omhet/redux-signalr#1]
Hi there,

I love your library, and I'm using it in a testing situation. One tip you might want to add is the following: In order to dispatch events that are created using [createAsyncThunk ](https://redux-toolkit.js.org/api/createAsyncThunk)(link) your typing is too strict (when using TS). 

I've used the following code (and it works and compiles without issues:
```
const callbacks = withCallbacks()
  .add('ReceiveMessage', (msg: string) => (dispatch) => {
    dispatch(doMyAsyncThunkThing());
  });
```

Note: No typing on "dispatch is neccesary, people using RTK will have no issues with this.

**Comment by Omhet** [comment]
Hi,

Thanks for your feedback! I'm happy to know someone actually uses this package :)

I'll try to investigate on typings and RTK. Although can't promise that I fix it anytime soon, so any help you may be able to extend in this regard will be much appreciated :)

**Comment by ghost** [comment]
No worries - this is exactly what I need, and I really think you did a very nice job in creating something that looks nice, is easy to read, and fits right in the redux-mindscape. I'll create a PR :)!

**Comment by Omhet** [comment]
Thanks!
