### ISSUE TITLE
SignalR should be a peerDependency

### ISSUE THREAD

**Issue by maciejewiczow** [Omhet/redux-signalr#14]
SignalR should be listed as a peerDependency in `package.json`, because this package adds a new funcionality on top of SignalR, not uses it internally to work. The relationship here is the same as between `react`, `redux` and `react-redux`. This will also remove the need to re-export the entirety of SignalR from this package.

**Comment by Omhet** [comment]
@maciejewiczow  Yeah, that's actually a pretty good idea. Thanks!
You can do this change yourself if you wish. Any help appreciated 😊
