### ISSUE TITLE
Add Github badges in README

### ISSUE THREAD

**Issue by Omhet** [Omhet/redux-signalr#8]
Here is the collection of labels: https://gist.github.com/tterb/982ae14a9307b80117dbf49f624ce0e8
 
We need:
- License
- NPM

**Comment by SPOCTONE** [comment]
Hey! I can work on this :) 
P.S. I noticed that you haven't added a license yet to your repository. I would advice you to add one and in the meantime I'll add an NPM label. 
Or let me add a license of your choice by editing this issue on your end. so that all the work will get done in one PR only.

**Comment by kairb** [comment]
Hey, I'm a first timer to open source,

Can I work on this? :D

**Comment by Omhet** [comment]
@SPOCTONE Hi!
LICENSE has been added

**Comment by Omhet** [comment]
@kairb Hi!

I think, @SPOCTONE is on it already.

@SPOCTONE  Will you work on this or let @kairb do it?

**Comment by SPOCTONE** [comment]
awesome! pls assign me and I'll start working on the issue ASAP

**Comment by kairb** [comment]
Didn't see this. Already opened a PR :(

**Comment by Omhet** [comment]
Thanks! Merged

**Comment by SPOCTONE** [comment]
> Didn't see this. Already opened a PR :(

no problem bro. It happens 😅
